### ISSUE TITLE
JSDoc / Documentation 

### ISSUE THREAD

**Issue by accraze** [accraze/machine-translator#3]
The code isn't even commented yet.... would like to setup JSDoc

**Comment by hillaryfraley** [comment]
Sure, let me see if I can help. Two questions:
1. You want the JSDoc comments in this file? https://github.com/accraze/machine-translator/tree/master/src
2. Do you want basic descriptions or the full documentation tags?

**Comment by accraze** [comment]
Hey @hillaryfraley,

1) Yes comments in that file would be great.
2) Just basic descriptions are fine for now

**Comment by hillaryfraley** [comment]
OK...I was able to do a little. I'm not that great with JavaScript, so I had some trouble figuring out what different parts did. I basically used the comments you already had in there, so there's still a lot missing.

**Comment by accraze** [comment]
This looks great for now @hillaryfraley! Thanks!

closed by #98
